<?php
require_once dirname(__DIR__) . '/includes/config/init.php';

// Ensure the admin is logged in
if (!isset($_SESSION['admin_id'])) {
    header('Location: login.php');
    exit();
}

// Handle AJAX requests for notification badge updates
if (isset($_GET['ajax']) && $_GET['ajax'] == '1') {
    try {
        $unread_query = $pdo->prepare("SELECT COUNT(*) FROM notifications WHERE admin_id = ? AND is_read = 0");
        $unread_query->execute([$_SESSION['admin_id']]);
        $unread_count = $unread_query->fetchColumn();
        
        header('Content-Type: application/json');
        echo json_encode(['unread_count' => (int)$unread_count]);
        exit();
    } catch (PDOException $e) {
        header('Content-Type: application/json');
        echo json_encode(['unread_count' => 0]);
        exit();
    }
}

$message = '';
$error = '';

// Check if notification was deleted or cleared
if (isset($_GET['deleted']) && $_GET['deleted'] == '1') {
    $message = "Notification deleted successfully!";
} elseif (isset($_GET['cleared']) && $_GET['cleared'] == '1') {
    $message = "All notifications cleared successfully!";
}

// Handle mark as read action
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['mark_read'])) {
    $notification_id = intval($_POST['notification_id']);
    
    try {
        $stmt = $pdo->prepare("UPDATE notifications SET is_read = 1 WHERE id = ? AND admin_id = ?");
        $stmt->execute([$notification_id, $_SESSION['admin_id']]);
        $message = "Notification marked as read!";
    } catch (PDOException $e) {
        $error = "Error updating notification: " . $e->getMessage();
    }
}

// Handle mark all as read
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['mark_all_read'])) {
    try {
        $stmt = $pdo->prepare("UPDATE notifications SET is_read = 1 WHERE admin_id = ? AND is_read = 0");
        $stmt->execute([$_SESSION['admin_id']]);
        $message = "All notifications marked as read!";
    } catch (PDOException $e) {
        $error = "Error updating notifications: " . $e->getMessage();
    }
}

// Handle clear all notifications (for testing)
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['clear_all_notifications'])) {
    try {
        $stmt = $pdo->prepare("DELETE FROM notifications WHERE admin_id = ?");
        $stmt->execute([$_SESSION['admin_id']]);
        $message = "All notifications cleared!";
        
        // Redirect to prevent page reload issues
        header("Location: " . $_SERVER['PHP_SELF'] . "?cleared=1");
        exit();
    } catch (PDOException $e) {
        $error = "Error clearing notifications: " . $e->getMessage();
    }
}

// Handle delete notification
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['delete_notification'])) {
    $notification_id = intval($_POST['notification_id']);
    
    try {
        $stmt = $pdo->prepare("DELETE FROM notifications WHERE id = ? AND admin_id = ?");
        $stmt->execute([$notification_id, $_SESSION['admin_id']]);
        $message = "Notification deleted!";
        
        // Redirect to prevent page reload issues
        header("Location: " . $_SERVER['PHP_SELF'] . "?deleted=1");
        exit();
    } catch (PDOException $e) {
        $error = "Error deleting notification: " . $e->getMessage();
    }
}

// Get notifications
$notifications_query = $pdo->prepare("
    SELECT * FROM notifications 
    WHERE admin_id = ? 
    ORDER BY created_at DESC 
    LIMIT 50
");
$notifications_query->execute([$_SESSION['admin_id']]);
$notifications = $notifications_query->fetchAll(PDO::FETCH_ASSOC);

// Debug: Log notification count (remove in production)
error_log("Admin " . $_SESSION['admin_id'] . " has " . count($notifications) . " notifications");

// Include header after all redirect logic
include INCLUDES_PATH . '/templates/admin_header.php';

// Get unread count
$unread_count_query = $pdo->prepare("SELECT COUNT(*) FROM notifications WHERE admin_id = ? AND is_read = 0");
$unread_count_query->execute([$_SESSION['admin_id']]);
$unread_count = $unread_count_query->fetchColumn();

// Sample notifications are no longer auto-created
// Notifications will only appear when they are actually generated by the system
?>

<style>
    .notifications-container {
        max-width: 1000px;
        margin: 0 auto;
        padding: 20px;
    }
    
    .notifications-card {
        background: white;
        border-radius: 15px;
        padding: 30px;
        box-shadow: 0 10px 30px rgba(0,0,0,0.1);
        margin-bottom: 30px;
    }
    
    .notifications-header {
        text-align: center;
        margin-bottom: 30px;
        padding-bottom: 20px;
        border-bottom: 2px solid #e9ecef;
    }
    
    .notifications-icon {
        width: 80px;
        height: 80px;
        border-radius: 50%;
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        display: flex;
        align-items: center;
        justify-content: center;
        margin: 0 auto 20px;
        font-size: 2rem;
        color: white;
        position: relative;
    }
    
    .notification-badge {
        position: absolute;
        top: -5px;
        right: -5px;
        background: #dc3545;
        color: white;
        border-radius: 50%;
        width: 25px;
        height: 25px;
        display: flex;
        align-items: center;
        justify-content: center;
        font-size: 0.8rem;
        font-weight: bold;
    }
    
    .alert {
        border-radius: 10px;
        padding: 15px 20px;
        margin-bottom: 20px;
    }
    
    .notification-item {
        background: #f8f9fa;
        border-radius: 10px;
        padding: 20px;
        margin: 15px 0;
        border-left: 4px solid #3498db;
        transition: all 0.3s ease;
    }
    
    .notification-item:hover {
        transform: translateY(-2px);
        box-shadow: 0 5px 15px rgba(0,0,0,0.1);
    }
    
    .notification-item.unread {
        background: #e3f2fd;
        border-left-color: #2196f3;
    }
    
    .notification-item.order {
        border-left-color: #4caf50;
    }
    
    .notification-item.service {
        border-left-color: #ff9800;
    }
    
    .notification-item.stock {
        border-left-color: #f44336;
    }
    
    .notification-item.system {
        border-left-color: #9c27b0;
    }
    
    .notification-header {
        display: flex;
        justify-content: between;
        align-items: center;
        margin-bottom: 10px;
    }
    
    .notification-title {
        font-weight: bold;
        color: #2c3e50;
        margin: 0;
    }
    
    .notification-time {
        color: #6c757d;
        font-size: 0.9rem;
    }
    
    .notification-message {
        color: #495057;
        margin: 10px 0;
    }
    
    .notification-actions {
        display: flex;
        gap: 10px;
        margin-top: 15px;
    }
    
    .btn-sm {
        padding: 5px 15px;
        font-size: 0.8rem;
        border-radius: 15px;
    }
    
    .btn-primary {
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        border: none;
    }
    
    .btn-secondary {
        background: #6c757d;
        border: none;
    }
    
    .btn-danger {
        background: #dc3545;
        border: none;
    }
    
    .btn-success {
        background: #28a745;
        border: none;
    }
    
    .empty-state {
        text-align: center;
        padding: 60px 20px;
        color: #6c757d;
    }
    
    .empty-state i {
        font-size: 4rem;
        margin-bottom: 20px;
        opacity: 0.5;
    }
    
    .stats-row {
        display: flex;
        justify-content: space-around;
        margin: 20px 0;
        padding: 20px;
        background: #f8f9fa;
        border-radius: 10px;
    }
    
    .stat-item {
        text-align: center;
    }
    
    .stat-number {
        font-size: 2rem;
        font-weight: bold;
        color: #2c3e50;
    }
    
    .stat-label {
        color: #6c757d;
        font-size: 0.9rem;
    }
</style>

<div class="notifications-container">
    <div class="notifications-card">
        <div class="notifications-header">
            <div class="notifications-icon">
                <i class="fas fa-bell"></i>
                <?php if ($unread_count > 0): ?>
                    <div class="notification-badge"><?php echo $unread_count; ?></div>
                <?php endif; ?>
            </div>
            <h1>Notifications</h1>
            <p class="text-muted">Stay updated with system alerts and important messages</p>
        </div>

        <?php if ($message): ?>
            <div class="alert alert-success">
                <i class="fas fa-check-circle"></i> <?php echo htmlspecialchars($message); ?>
            </div>
        <?php endif; ?>

        <?php if ($error): ?>
            <div class="alert alert-danger">
                <i class="fas fa-exclamation-triangle"></i> <?php echo htmlspecialchars($error); ?>
            </div>
        <?php endif; ?>

        <!-- Notification Stats -->
        <div class="stats-row">
            <div class="stat-item">
                <div class="stat-number"><?php echo count($notifications); ?></div>
                <div class="stat-label">Total</div>
            </div>
            <div class="stat-item">
                <div class="stat-number"><?php echo $unread_count; ?></div>
                <div class="stat-label">Unread</div>
            </div>
            <div class="stat-item">
                <div class="stat-number"><?php echo count($notifications) - $unread_count; ?></div>
                <div class="stat-label">Read</div>
            </div>
        </div>

        <!-- Action Buttons -->
        <div class="text-center mb-4">
            <?php if ($unread_count > 0): ?>
                <form method="POST" style="display: inline;">
                    <button type="submit" name="mark_all_read" class="btn btn-success me-2">
                        <i class="fas fa-check-double"></i> Mark All as Read
                    </button>
                </form>
            <?php endif; ?>
            
            <?php if (!empty($notifications)): ?>
                <form method="POST" style="display: inline;" onsubmit="return confirm('Are you sure you want to clear ALL notifications? This action cannot be undone.')">
                    <button type="submit" name="clear_all_notifications" class="btn btn-danger">
                        <i class="fas fa-trash"></i> Clear All Notifications
                    </button>
                </form>
            <?php endif; ?>
        </div>

        <!-- Notifications List -->
        <?php if (!empty($notifications)): ?>
            <?php foreach ($notifications as $notification): ?>
                <div class="notification-item <?php echo $notification['is_read'] ? '' : 'unread'; ?> <?php echo $notification['type']; ?>">
                    <div class="notification-header">
                        <h5 class="notification-title">
                            <?php if ($notification['type'] == 'order'): ?>
                                <i class="fas fa-shopping-cart text-success"></i>
                            <?php elseif ($notification['type'] == 'service'): ?>
                                <i class="fas fa-tools text-warning"></i>
                            <?php elseif ($notification['type'] == 'offer'): ?>
                                <i class="fas fa-gift text-info"></i>
                            <?php elseif ($notification['type'] == 'stock'): ?>
                                <i class="fas fa-exclamation-triangle text-danger"></i>
                            <?php elseif ($notification['type'] == 'system'): ?>
                                <i class="fas fa-cog text-primary"></i>
                            <?php endif; ?>
                            <?php echo htmlspecialchars($notification['title']); ?>
                        </h5>
                        <span class="notification-time">
                            <?php echo date('M j, Y g:i A', strtotime($notification['created_at'])); ?>
                        </span>
                    </div>
                    
                    <div class="notification-message">
                        <?php echo htmlspecialchars($notification['message']); ?>
                    </div>
                    
                    <div class="notification-actions">
                        <?php if (!$notification['is_read']): ?>
                            <form method="POST" style="display: inline;">
                                <input type="hidden" name="notification_id" value="<?php echo $notification['id']; ?>">
                                <button type="submit" name="mark_read" class="btn btn-primary btn-sm">
                                    <i class="fas fa-check"></i> Mark as Read
                                </button>
                            </form>
                        <?php endif; ?>
                        
                        <form method="POST" style="display: inline;">
                            <input type="hidden" name="notification_id" value="<?php echo $notification['id']; ?>">
                            <button type="submit" name="delete_notification" class="btn btn-danger btn-sm" 
                                    onclick="return confirm('Are you sure you want to delete this notification?')">
                                <i class="fas fa-trash"></i> Delete
                            </button>
                        </form>
                    </div>
                </div>
            <?php endforeach; ?>
        <?php else: ?>
            <div class="empty-state">
                <i class="fas fa-bell-slash"></i>
                <h4>No Notifications</h4>
                <p>You're all caught up! No new notifications at the moment.</p>
            </div>
        <?php endif; ?>

        <!-- Action Buttons -->
        <div class="text-center mt-4">
            <a href="index.php" class="btn btn-secondary">
                <i class="fas fa-arrow-left"></i> Back to Dashboard
            </a>
        </div>
    </div>
</div>

<?php include INCLUDES_PATH . '/templates/admin_footer.php'; ?>

